
name: ci-core-go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  security-events: write
jobs:
  build-test-sec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/core-go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.7'
      - name: Build & Test
        run: |
          go mod tidy
          go vet ./...
          go test ./... -race -cover
      - name: Install gosec (via go install)
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: SAST - gosec
        run: gosec ./...
      - name: SAST - Semgrep (Go)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/golang
      - name: SCA - govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          ~/go/bin/govulncheck ./...
      - name: Build Docker image
        run: docker build -t core-go:ci .
      - name: Trivy FS scan (repo)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          exit-code: '1'
          format: 'table'
      - name: Trivy Image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'core-go:ci'
          ignore-unfixed: true
          exit-code: '1'
          format: 'table'
          severity: 'CRITICAL'
      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name core core-go:ci
          sleep 5
      - name: DAST - OWASP ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
      #- name: Secret scan - Gitleaks
      #  uses: zricethezav/gitleaks-action@v2
      #  with:
      #    args: detect --no-git -v --redact
      - name: SBOM (CycloneDX via Trivy)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'core-go:ci'
          format: 'cyclonedx'
          output: 'sbom-core-go.cdx.json'
          exit-code: '0'
      - uses: actions/upload-artifact@v4
        with:
          name: core-go-security-reports
          path: sbom-core-go.cdx.json
      - if: always()
        run: docker rm -f core || true
